import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import Link from 'next/link';
import Navbar from "@/pages/components/Navbar";
import { log } from "console";
export default function Home() {
  const [cards, setCards] = useState<any[]>([]);
  const [flippedCards, setFlippedCards] = useState<number[]>([]);
  const [matchedCards, setMatchedCards] = useState<number[]>([]);
  const [score, setScore] = useState<number>(0);
  const [scores, setScores] = useState<{ username: string, score: number }[]>([]);
  useEffect(() => {
    console.log("Running useEffect. This runs when the component loads the first time")
    fetch("http://localhost:3000/api/cards")
      .then((response: Response) => {
        if (response.ok === false) throw new Error(`Getting cards failed with HTTP error, status: ${response.status}`);
        return response.json();
      }, (reason: any) => {
      })
      .then(cardsFromBackend => {
        const eightCards = cardsFromBackend.slice(0, 8);
        const duplicatedCards = [...eightCards, ...eightCards];
        const shuffledCards = duplicatedCards.sort(() => Math.random() - 0.5);
        setCards(shuffledCards);
      }, (reason: any) => {
      })
  }, [])
  const cardClick = (index: number) => {
    console.log(score);
    if (
      flippedCards.length === 2 ||
      flippedCards.includes(index) ||
      matchedCards.includes(index)
    ) {
      return;
    }
    const newFlipped = [...flippedCards, index];
    setFlippedCards(newFlipped);
    if (newFlipped.length === 2) {
      const firstCard = cards[newFlipped[0]];
      const seconCard = cards[newFlipped[1]];
      setScore(prev => prev + 1)
      if (firstCard.id === seconCard.id) {
        setMatchedCards((prev) => [...prev, ...newFlipped]);
      }
      setTimeout(setFlippedCards, 800, []);
    }
  };
  const checkGameIsFinished = () => {
    const name = prompt("Well done! Input name please")
    console.log("user name:", name)
    fetch("http://localhost:3000/api/score", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        username: name,
        score: score,
      }),
    })
      .then((response: Response) => {
        if (response.ok === false) throw new Error(`Getting cards failed with HTTP error, status: ${response.status}`);
        return response.json();
      }, (reason: any) => {
        console.error("netwerk requst faild", reason)
      })
      .then(
        (responseJson) => {
          console.log("score submitted successfully with response:", responseJson);
        },
        (reason: any) => {
          console.error("Failed to parse JSON", reason);
        }
      );
  }
  //> 1 OR ===  // 
  useEffect(() => {
    if (cards.length > 0 && matchedCards.length === cards.length) {
      setTimeout(checkGameIsFinished, 500,);
    }
  }, [matchedCards]);
  const restartGame = () => {
    setScore(0);
    setFlippedCards([]);
    setMatchedCards([]);
  }
  return (
    <>
      <Head>
        <title>Create Memory Game </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div
        className={`${styles.page}`}
      >
        <div className={styles.titlePartPart}>
          <h1 className="restartbuttonbutton">Memory Game</h1>
        </div>
        <div className={styles.titlePart}>
          <ul>
            <li>
              <button className={styles.restartbutton}>Score:{score}</button>
            </li>
            <li>
              <button className={styles.restartbutton} onClick={restartGame}>  Restart</button>
            </li>
          </ul>
        </div>
        <div className={styles.cardsWrapper}>
          {cards.map((card, index) => (
            <div
              key={index}
              className={styles.card}
              onClick={() => cardClick(index)}
            >
              {flippedCards.includes(index) || matchedCards.includes(index) ? (
                <Image
                  src={`http://localhost:3000/images/${card.url}`}
                  alt={card.title || "card"}
                  width={100}
                  height={100}
                />
              ) : (
                <div className={styles.cardsback}></div>
              )}
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
